### ISSUE TITLE
Cannot compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by danielemarino** [lefcha/imapfilter#173]
Hi.

I am trying to compile imapfilter on Ubuntu 16.04, to get rid of segmentation fault error, but without success. This is what I get

```
daniele@mypc:~/imapfilter-master$ make
cd src && make all
make[1]: Entering directory '/home/daniele/imapfilter-master/src'
cc -o imapfilter   auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -ldl -llua -lpcre -lssl -lcrypto
/usr/bin/ld: cannot find -llua
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'imapfilter' failed
make[1]: *** [imapfilter] Error 1
make[1]: Leaving directory '/home/daniele/imapfilter-master/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

All the needed libraries are installed. As suggested on a website I tried to add `INCDIRS` and `LIBLUA` switches. This is what I get

```
daniele@mypc:~/imapfilter-master$ make INCDIRS=-I/usr/include/lua5.2 LIBLUA=-llua5.2
cd src && make all
make[1]: Entering directory '/home/daniele/imapfilter-master/src'
cc -o imapfilter   auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -ldl -llua5.2 -lpcre -lssl -lcrypto
core.o: In function `ifcore_append':
core.c:(.text+0x103d): undefined reference to `lua_objlen'
core.o: In function `luaopen_ifcore':
core.c:(.text+0x1c45): undefined reference to `luaL_register'
pcre.o: In function `ifre_free':
pcre.c:(.text+0x55): undefined reference to `lua_rotate'
pcre.o: In function `ifre_exec':
pcre.c:(.text+0x22f): undefined reference to `lua_rotate'
pcre.c:(.text+0x24e): undefined reference to `lua_rotate'
pcre.c:(.text+0x26d): undefined reference to `lua_rotate'
pcre.c:(.text+0x2a2): undefined reference to `lua_rotate'
pcre.o:pcre.c:(.text+0x3c8): more undefined references to `lua_rotate' follow
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'imapfilter' failed
make[1]: *** [imapfilter] Error 1
make[1]: Leaving directory '/home/daniele/imapfilter-master/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

Any suggestion?

ps: the same happens if I try to use lua 5.1 or 5.3

**Comment by lefcha** [comment]
Have you installed the relevant development libraries? For example [liblua5.2-dev](https://packages.ubuntu.com/xenial/liblua5.2-dev).

**Comment by Xaelias** [comment]
Has the same issue. Although after install liblua5.3-def and running:
- make INCDIRS=-I/usr/include/lua5.3 LIBLUA=-llua5.3
- sudo make INCDIRS=-I/usr/include/lua5.3 LIBLUA=-llua5.3 install

Everything seems to be working. Hope that helps.

**Comment by ccomincini** [comment]
The same for Debian.
Thankyou
