### ISSUE TITLE
Fail to build with openssl 1.1.0

### ISSUE THREAD

**Issue by sylvestre** [lefcha/imapfilter#141]
```

cc -Wall -Wextra -O -DCONFIG_SHAREDIR='"/usr/share/imapfilter"' -I/usr/include/lua5.2    -c -o auth.o auth.c
auth.c: In function 'auth_cram_md5':
auth.c:23:11: error: storage size of 'hmac' isn't known
  HMAC_CTX hmac;
```

Reported initially here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828350

**Comment by lefcha** [comment]
Thanks for reporting this!

Closed by b14bd877967610568b450be3da26d25d7c974c8c.
